---
# - apt: update_cache=yes
#   become: yes

- name: Get system name
  command: "uname -r"
  register: sysname

- name: Install essentials
  apt: pkg={{item}} state=present update_cache=no
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-virtual
    - "linux-image-extra-{{ sysname.stdout }}"
    - python3
    - python-pip
    - bridge-utils

- name: Install docker repo
  become: yes
  shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' | tee /etc/apt/sources.list.d/docker.list

- apt: update_cache=yes
  become: yes

- name: Install Docker
  become: yes
  apt: pkg=docker-engine state=present update_cache=no force=yes

- name: Install Docker componse
  become: yes
  pip: name=docker-compose

- name: Start docker
  service: name=docker state=started
