---
# - apt: update_cache=yes
#   become: yes

- name: Get system name
  command: "uname -r"
  register: sysname

- name: Install essentials
  apt: pkg={{item}} state=present update_cache=no
  become: yes
  with_items:
    - apt-transport-https 
    - ca-certificates
    - linux-image-extra-virtual
    - "linux-image-extra-{{ sysname.stdout }}"
    - python3
    - python-pip

- name: Install docker apt key
  become: yes
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Install docker repo
  become: yes
  shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' | tee /etc/apt/sources.list.d/docker.list

# - apt: update_cache=yes
#   become: yes

- name: Install Docker
  become: yes
  apt: pkg=docker-engine state=present update_cache=no

- name: Install Docker componse
  become: yes
  pip: name=docker-compose

- name: Start docker
  service: name=docker state=started