apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-server
  namespace: chaos-gocd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gocd-server
    spec:
      containers:
      - name: frigate-gocd-server
        image: registry.walkure.net:5000/frigate:latest
        ports:
        - containerPort: 8153
        - containerPort: 8154
