apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-server
  namespace: chaos-gocd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gocd-server
    spec:
      containers:
      - name: frigate-gocd-server
        image: registry.walkure.net:5000/frigate:latest
        volumeMounts:
        - name: config-store
          mountPath: /etc/go/
        - name: artifacts-store
          mountPath: /var/lib/go-server/
        ports:
        - containerPort: 8153
        - containerPort: 8154
      volumes:
      - name: config-store
        persistentVolumeClaim:
          claimName: gocd-server-config-pvc
      - name: artifacts-store
        persistentVolumeClaim:
          claimName: gocd-server-artifacts-pvc
