kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-system-kube-registry-pv
  labels:
    #kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "kube-registry-volume"
spec:
  capacity:
    storage: {{ pillar['cluster_registry_disk_size'] }}
  accessModes:
    - ReadWriteOnce
  nfs:
    pdName: "{{ pillar['cluster_registry_disk_name'] }}"
    fsType: "ext4"
