kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-system-kube-registry-pv
  labels:
    #kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "kube-registry-volume"
spec:
  capacity:
    #storage: {{ pillar['cluster_registry_disk_size'] }}
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /registry
    server: 172.16.0.253
