---
- name: Download go lang
  shell: cd /tmp && ([ -f go1.7.4.linux-amd64.tar.gz ] || [ -f /usr/local/go/bin/go ] || wget https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz)

- name: extract go lang
  become: yes
  shell: cd /tmp && tar -xf go1.7.4.linux-amd64.tar.gz -C /usr/local

- name: add go lang binaries to PATH
  shell: export PATH=$PATH:/usr/local/go/bin

- name: Clone kubernetes repo
  shell: cd ~ && ([ -d kubernetes ] || git clone https://github.com/GoogleCloudPlatform/kubernetes.git)

- name: Install kube cluster
  shell: cd ~/kubernetes/cluster/ubuntu && ([ -d binaries ] || ./download-release.sh)

- name: add kube binaries to PATH
  shell: export PATH=$PATH:~/kubernetes/cluster/ubuntu/binaries

- name: Install NFS Server
  apt: pkg=nfs-kernel-server state=present update_cache=no

- name: Create NFS directorys
  become: yes
  shell: mkdir -p /export/registry && mkdir -p /export/db_storage

- name: Copy exports config
  become: yes
  shell: 'echo /export       172.16.0.0/24(rw,fsid=0,insecure,no_subtree_check,async,no_root_squash)
  /export/registry 172.16.0.0/24(rw,nohide,insecure,no_subtree_check,async,no_root_squash)" >> /etc/exports'

- name: Restarr nfs-server
  service: name=nfs-kernel-server state=restarted

- name: Reload nfs exports
  become: yes
  shell: 'exportfs -ra'
